### ISSUE TITLE
Support for EPCQ serial flash

### ISSUE THREAD

**Issue by alpensalamander** [dimag0g/nios_duino#1]
I love the Project and it works well with my Cyclone IV Dev Board. Now with my CYC1000 Board with external RAM the NIOS Core doesn't work with the EPCS and would need an EPCQ instead. Could somebody tell me what to do to get this Board to work?

**Comment by dimag0g** [comment]
Hi, the software will likely work just the same, it's the Qsys project that must be adapted in order to use EPCQ. AFAIK EPCQ can be used the same way as EPCS (with a bootloader copying the software from Flash to RAM), and additionally it can be configured to execute the software directly from the Flash. I'll see if I can get EPCQ component to work with my hardware, or eventually I'll get that board you mention, then I'll update the Qsys file, but it will take a while. You're welcome to contribute if you figure it out first.

**Comment by alpensalamander** [comment]
So I tried it myself but ran into an error.
I included the epcq controller like that:
![Contents](https://user-images.githubusercontent.com/46628514/57630646-45552000-759e-11e9-8c4e-3b804c747a8f.PNG)
![Address](https://user-images.githubusercontent.com/46628514/57630660-4a19d400-759e-11e9-9217-408ce7e48df1.PNG)
![Vector](https://user-images.githubusercontent.com/46628514/57630662-4be39780-759e-11e9-8272-e1158b75ae0a.PNG)
And got this error when creating the Nios project in Eclipse:
![Message](https://user-images.githubusercontent.com/46628514/57630721-6fa6dd80-759e-11e9-9a31-b4dd099b5e80.PNG)

Here are my project files:
[NIOSDuino10.zip](https://github.com/dimag0g/nios_duino/files/3173507/NIOSDuino10.zip)

**Comment by alpensalamander** [comment]
This is my Error:
SEVERE: [Error] altera_hal_linkerx_generator: Required linker section mappings do not exist: "[.entry, .exceptions, .rodata, .rwdata, .text, .bss, .heap, .stack]"
SEVERE: [Error] altera_hal_linkerx_generator: Required linker section mappings do not exist: "[.entry, .exceptions, .rodata, .rwdata, .text, .bss, .heap, .stack]"
SEVERE: nios2-bsp-create-settings failed.
nios2-bsp: nios2-bsp-create-settings failed

**Comment by dimag0g** [comment]
Your settings suggest that you're trying to use a boot copier to copy EPCQ contents to SDRAM and execute the code from SDRAM. In this case you need to make sure that all linker sections are set to SDRAM (Linker Script tab in BSP editor), and all advanced linker settings ("allow code at reset", etc) are **un**checked.

Alternatively, you can try to set up your system to execute the code in-place from EPCQ. That would require setting the reset vector to avl_mem instead of avl_csr, and adjusting linker settings as described e.g. here: https://docplayer.net/51472292-Nios-ii-processor-booting-from-altera-serial-flash-epcq.html

Edit: I just made a system with "Altera Serial Flash Controller" which supports EPCS16 (instead of "Altera Serial Flash Controller II" that you use and that only supports EPCQxx), and it indeed works as expected, including in-place execution.

**Comment by alpensalamander** [comment]
So I checked out the new version with a MAX1000 and free V18.1, but cannot program the processor. First I added a pll, to have 48 instead of 12MHz and  I don't know what to do with clk reset, cpu reset, adc pll locked and the conduits from the pll

**Comment by alpensalamander** [comment]
This is also fixed, by the way
